<a href="https://colab.research.google.com/github/Sachinvt/Sachinvt/blob/main/Numpy%20%26%20Pandas%20coding_I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

You have to write a Python program which does the following:

⚫ takes a list as input

• converts the list into a Pandas Series

• reshapes the Series into a dataframe of the order m x n, i.e. the dataframe has m rows and n columns

Input Format

• The first line contains two space-separated integers, representing the values of m and n respectively.

• The second line contains space-separated integers, which represent the elements of the list

Constraints

• 2 <= m, n <= 10

• The product of m and n should be equal to the length of the input list

Output Format

• If the product of m and n equals the length of the input list, print the converted dataframe

• If the product of m and n is NOT EQUAL to the length of the input list, print the message "Weird Order!"

Evaluation Parameters

2 3

1 2 3

4 5 6 7 8

Sample Output 1

Weird Order!

Explanation 1

Since the product of m and n is NOT EQUAL to the length of the input list, hence print "Weird Order!"

Sample Input 2

2 4

1 2 3 4 5 6 7 8

Sample Output 2

0 1 2 3

0 1 2 3 4

1 5 6 7 8

Explanation 2

Apart from the first column and first row [index] (containing the values 0 to 1 and 0 to 3 respectively), you can see that the rest of the elements have been reshaped to form a dataframe of 2 rows and 4 columns

In [1]:
import pandas as pd

# Read input from STDIN
m, n = map(int, input().split())
values = list(map(int, input().split()))

# Check if the product of m and n is equal to the length of the input list
if m * n != len(values):
    print("Weird Order!")
else:
    # Convert the list to a Pandas Series
    series = pd.Series(values)
    # Reshape the Series into a DataFrame of order m x n
    df = pd.DataFrame(series.values.reshape(m, n))
    print(df)


2 3
1 2 3 4 5 6
   0  1  2
0  1  2  3
1  4  5  6


Write a python program that does the following

• takes two lists as input list1 and list2

• creates two Pandas Series out of them

• stacks / concatenates both Series vertically and horizontally, along the column axis (axis = 1)

Input Format

• The first line contains space-separated values, which represent the elements of the first list list1

N

• The second line contains space-separated values, which represent the elements of the second list list2

Constraints

• length of list1 = length of list2

Output Format

• Print the dataframe containing the required output, with list1 being the first column and list2 being the second column

• If the above constraint is NOT satisfied, print NaN for all missing values

Evaluation Parameters

Sample Input 1
01234

abcde

Sample Output 1

01

11 b

2 2 c

3

3

d

e

44

Explanation #1

• Both lists are converted into Series and then stacked against each other.

• Then, the stacked/concatenated DataFrame is printed to STDOUT.

Sample Input 2

0123

abcde

Sample Output 2

01

ea

1 b

2

C

3 d

e

1

2

3

4 NaN

Explanation #2

• Both lists are converted into Series and then stacked against each other.

• Then, the stacked/concatenated DataFrame is printed to STDOUT.

• The missing value of list1 corresponding to that of list2 has been printed as NaN.

In [2]:
import pandas as pd

# Function to create pandas series and concatenate them
def concatenate_lists(list1, list2):
    # Check if length of lists is the same
    if len(list1) != len(list2):
        print("NaN")  # Print NaN if constraint is not satisfied
        return

    # Create pandas series from lists
    series1 = pd.Series(list1)
    series2 = pd.Series(list2)

    # Concatenate series vertically
    concatenated_vertically = pd.concat([series1, series2], axis=0)

    # Concatenate series horizontally
    concatenated_horizontally = pd.concat([series1, series2], axis=1)

    # Print concatenated dataframes
    print(concatenated_vertically)
    print("\n")
    print(concatenated_horizontally)

# Read input lists
list1 = list(input().strip())
list2 = list(input().strip())

# Call function to concatenate lists
concatenate_lists(list1, list2)


0 1 2 3 4
a b c d e
0    0
1     
2    1
3     
4    2
5     
6    3
7     
8    4
0    a
1     
2    b
3     
4    c
5     
6    d
7     
8    e
dtype: object


   0  1
0  0  a
1      
2  1  b
3      
4  2  c
5      
6  3  d
7      
8  4  e


Create a NumPy program to allocate seats in a classroom. Given the number of rows and columns in a classroom, return an array where each seat is numbered sequentially from left to right, top to bottom.

Input:

Rows:3

Columns:4

Output: [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [3]:
import numpy as np

def allocate_seats(rows, columns):
    # Calculate the total number of seats
    total_seats = rows * columns

    # Create a sequential array representing the seats
    seat_array = np.arange(1, total_seats + 1)

    # Reshape the array to match the specified number of rows and columns
    seat_allocation = seat_array.reshape(rows, columns)

    return seat_allocation

# Input rows and columns
rows = 3
columns = 4

# Allocate seats in the classroom
allocated_seats = allocate_seats(rows, columns)

# Output the allocated seats
print(allocated_seats)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Write a Numpy program to analyse
a set of temperature data (in degrees Celsius) for a city. Calculate the average temperature, the variance, and identify the days with temperatures above the 90th - percentile.

Note: Round off the answer to two decimal places.

Input: [22, 24, 28, 32, 31, 30, 35, 36, 38, 40, 41, 42, 43, 44, 45]

Output:

Average Temperature: 35.4

Variance: 50.11

Days above 90th percentile: [44, 45]

In [4]:
import numpy as np

def analyze_temperature_data(data):
    # Convert the input list to a NumPy array
    temperature_array = np.array(data)

    # Calculate average temperature
    avg_temperature = np.mean(temperature_array)

    # Calculate variance
    variance = np.var(temperature_array)

    # Calculate 90th percentile
    percentile_90 = np.percentile(temperature_array, 90)

    # Identify days with temperatures above the 90th percentile
    above_90th_percentile = temperature_array[temperature_array > percentile_90]

    return round(avg_temperature, 2), round(variance, 2), above_90th_percentile

# Input temperature data
temperature_data = [22, 24, 28, 32, 31, 30, 35, 36, 38, 40, 41, 42, 43, 44, 45]

# Analyze temperature data
average_temp, variance, above_90th_percentile = analyze_temperature_data(temperature_data)

# Output results
print("Average Temperature:", average_temp)
print("Variance:", variance)
print("Days above 90th percentile:", above_90th_percentile)


Average Temperature: 35.4
Variance: 50.11
Days above 90th percentile: [44 45]


Given a 4x4 matrix representing sensor readings over four days, normalize the data by subtracting the mean and dividing by the standard deviation for each day. Then, calculate the sum of the normalized values for each sensor.

Input:

[[10, 20, 30, 40],

[15, 25, 35, 45],

[20, 30, 40, 50],

[25, 35, 45, 55]]

Output:

Normalized Matrix:

[-1.3416407864998738, -0.4472135954999579, 0.4472135954999579, 1.3416407864998738]

[-1.3416407864998738, -0.4472135954999579, 0.4472135954999579, 1.3416407864998738]

[-1.3416407864998738, -0.4472135954999579, 0.4472135954999579, 1.3416407864998738]

[-1.3416407864998738, -0.4472135954999579, 0.4472135954999579, 1.3416407864998738]

Sum per Sensor: [-5.366563145999495, -1.7888543819998317, 1.7888543819998317, 5.366563145999495]



In [5]:
import numpy as np

def normalize_and_sum(sensor_readings):
    # Convert the input list to a NumPy array
    readings_array = np.array(sensor_readings)

    # Calculate mean and standard deviation for each day
    means = readings_array.mean(axis=1)
    stds = readings_array.std(axis=1)

    # Normalize the data
    normalized_data = (readings_array - means[:, np.newaxis]) / stds[:, np.newaxis]

    # Calculate sum per sensor
    sum_per_sensor = normalized_data.sum(axis=0)

    return normalized_data, sum_per_sensor

# Input data
sensor_readings = [[10, 20, 30, 40],
                   [15, 25, 35, 45],
                   [20, 30, 40, 50],
                   [25, 35, 45, 55]]

# Normalize the sensor readings and calculate sum per sensor
normalized_matrix, sum_per_sensor = normalize_and_sum(sensor_readings)

# Output normalized matrix
print("Normalized Matrix:")
print(normalized_matrix)

# Output sum per sensor
print("Sum per Sensor:", sum_per_sensor)


Normalized Matrix:
[[-1.34164079 -0.4472136   0.4472136   1.34164079]
 [-1.34164079 -0.4472136   0.4472136   1.34164079]
 [-1.34164079 -0.4472136   0.4472136   1.34164079]
 [-1.34164079 -0.4472136   0.4472136   1.34164079]]
Sum per Sensor: [-5.36656315 -1.78885438  1.78885438  5.36656315]


Develop a NumPy program to analyze flight path data. Given an array of altitude readings (in meters) over time, compute the total ascent and descent during the flight. Assume the flight starts and ends at the same altitude.

Input:

[100, 150, 200, 150, 100, 50, 100, 150]

Output:

Total Ascent: 200

Total Descent: 150

In [6]:
import numpy as np

def analyze_flight_path(altitude_readings):
    # Convert the altitude readings to a NumPy array
    altitude_array = np.array(altitude_readings)

    # Calculate the differences between consecutive altitude readings
    altitude_diff = np.diff(altitude_array)

    # Calculate total ascent (positive differences)
    total_ascent = np.sum(altitude_diff[altitude_diff > 0])

    # Calculate total descent (negative differences)
    total_descent = np.abs(np.sum(altitude_diff[altitude_diff < 0]))

    return total_ascent, total_descent

# Input data
altitude_readings = [100, 150, 200, 150, 100, 50, 100, 150]

# Analyze flight path
total_ascent, total_descent = analyze_flight_path(altitude_readings)

# Output results
print("Total Ascent:", total_ascent)
print("Total Descent:", total_descent)


Total Ascent: 200
Total Descent: 150


Write a simple program that takes  three integers as input :stp,enp and step, and uses these values to return evenly spaced values within the given interval.

Input Format

• The first line contains an integer - stp which represents the start of the interval.

• The second line contains an integer - enp which represents the end of the interval.

• The third line contains an integer - step which represents the spacing between consecutive values.

Constraints

• 1 <= stp < enp <= 105

• 2 <= step < enp <= 105

Output Format

• If the above constraints are not satisfied, print "Constraints are failing!"

• If the above constraints are satisfied, print each element of the list in a new line, as is generated using the condition described in the Problem Statement.

Sample Input

2

11

3

Sample Output 1

2

5

8

11

Explanation 1

• First element = 2

2+3=5

5+3=8

8+3=11

Since, the above elements fall in the given range as specified by the input, hence they will be printed to STDOUT, with each element on a new line.

Sample Input 2

2

11

13

Sample Output 2

Constraints are failing!

Explanation 2

Since, the value of step is more than the value for enp, hence

the message "Constraints are failing!" will be printed to STDOUT.


In [7]:
# Function to generate evenly spaced values within the given interval
def generate_values(stp, enp, step):
    # Check if constraints are satisfied
    if stp >= enp or step >= enp:
        print("Constraints are failing!")
        return

    # Generate values
    values = []
    current_value = stp
    while current_value <= enp:
        values.append(current_value)
        current_value += step

    # Print the generated values
    for val in values:
        print(val)

# Read input
stp = int(input())
enp = int(input())
step = int(input())

# Generate and print the values
generate_values(stp, enp, step)


2
11
3
2
5
8
11


The firm has recently launched various marketing campaigns for its clients. As part of the campaigns, the firm has delivered a certain number of marketing cold emails to the customer.

You are given some data related to the name of the client as the campaign name, the number of emails delivered as part of the campaign and the email open count for each campaign.

Your task here is to calculate the open rate for each campaign and print the output in the form of Boolean values for the open rates as follows:

• If the open rate for a campaign is greater than the mean open rate the output for that campaign should be "True"

• If the open rate for a campaign is lower than the mean open rate the output for that campaign should be "False"

Use pandas function and create a DataFrame from Dict of ndarrays / Lists

Input Format

• The first line contains an integer T, denoting the number of elements in the dictionary

• The second line contains T space-separated values containing data related to Campaign Name.

• The third line contains T space-separated values

• The third line contains containing data related to Number of Emails

• The fourth line contains T space-separated values containing data related to Email Open Rate.

Output Format

• Print the values as True/False as per the conditions provided in the problem statement

Evaluation Parameters

Sample Input

4

SoftBank Apple Microsoft Amazon

2845 3425 2942 4215

1253 3256 2100 1252

Sample Output

False

True

True

False

In [8]:
import pandas as pd

# Read input
T = int(input())
campaign_names = input().split()
num_emails = list(map(int, input().split()))
open_count = list(map(int, input().split()))

# Calculate open rate for each campaign
open_rate = [oc / ne for oc, ne in zip(open_count, num_emails)]

# Calculate mean open rate
mean_open_rate = sum(open_rate) / T

# Print output
for rate in open_rate:
    if rate > mean_open_rate:
        print("True")
    else:
        print("False")


4
SoftBank Apple Microsoft Amazon
2845 3425 2942 4215
1253 3256 2100 1252
False
True
True
False


In [9]:
pd.__version__

'1.5.3'